/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;

import java.util.ArrayList;

/* Generated by Together */
abstract public class Permit {

    /**
     * The name of the permit holder
     */
    private String permitHolder;

    /**
     * Counts the number of days on which the campus was entered while the
     * access barriers were in operation. Counting starts when the permit is
     * issued, and afresh at the start of each year.
     */
    private int noOfEntries = 0;

    /**
     * Counts the number of warnings issued to vehicles registered on this
     * permit.
     */
    private int warnings = 0;

    /**
     * False if the permit has not been suspended, and true if it has (on the
     * third warning).
     */
    private boolean suspended = false;

    /**
     * Set to false at the start of each day. Remains false until first entry of
     * a vehicle on this permit, when it is set true, and the vehicle is noted
     * in vehicleUsed. Used for checking that subsequent entries in the day are
     * the same vehicle (since exits are not monitored).
     */
    private boolean enteredToday = false;

    /**
     * Once a vehicle has entered on this permit on any day, this attribute
     * records the vehicle that entered, so that any subsequent entries
     * associated with this permit can be verified as the same vehicle (or at
     * least with the same registration number!). The attribute will be null
     * until a vehicle has entered.
     *
     * @clientCardinality 1
     * @directed true
     * @label Allowed today
     * @supplierCardinality 0..1
     */
    private Vehicle_info vehicleUsedToday;
    private String permitType;
    private String visitday;
    private String endday;

    /**
     * This holds references to all the Vehicle_info instances for the vehicles
     * registered to this permit. Note that any vehicle can be registered to
     * only one permit, but many vehicles may be registered to the same permit.
     * This attribute must be implemented by a collection data structure (such
     * as array, hash table,...).
     *
     * @clientCardinality 1
     * @directed true
     * @label Controls access of
     * @supplierCardinality 0..*
     */
    //private Vehicle_info permittedVehicles;
    private ArrayList permittedVehicles = new ArrayList();

    public Permit(String Cn) {
        this.permitType = permitType;
        permitHolder = Cn;
        noOfEntries = 0;
        warnings = 0;
        suspended = false;
        enteredToday = false;
        permittedVehicles = new ArrayList();
    }

    public void setPermitType(String permitType) {
        this.permitType = permitType;
    }

    public void setVisitday(String visitday) {
        this.visitday = visitday;
    }

    public void setEndday(String endday) {
        this.endday = endday;
    }

    public String getPermitType() {
        return permitType;
    }

    public String getVisitday() {
        return visitday;
    }

    public String getEndday() {
        return endday;
    }

    @Override
    public String toString() {
        return "Permit{" + "permitHolder=" + permitHolder + ", noOfEntries=" + noOfEntries + ", warnings=" + warnings +
                ", suspended=" + suspended + ", enteredToday=" + enteredToday + ", vehicleUsedToday=" + vehicleUsedToday +
                ", permitType=" + permitType + ", visitday=" + visitday + ", endday=" + endday + ", permittedVehicles=" +
                permittedVehicles + '}';
    }
}
