/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;
/* Generated by Together */

/**
 * For a description of Day visitors, follow hyperlink to the Administration use case for
 * issuing a new Day visitor permit.
 */
public class Day_visitor_permit extends Permit {
    /**
     * The name of the University member hosting the visit.
     */
    private String owenerName;
    private String visitDay;
    private String permitType;

    public Day_visitor_permit(String Cn, String On, String Vd) {
        //initialize the values 
        super(Cn);
        owenerName = On;
        visitDay = Vd;
        permitType = "Day Visitor";
        setPermitType(permitType);//Set the Permit Type
        setVisitday(Vd);//Set the visit day
    }
    
    @Override
    //ToString method for printing Regular visitor permit
    public String toString() {
        return "Day_visitor_permit{" + "owenerName=" + owenerName + ", visitDay=" + visitDay + ", permitType=" + permitType + '}';
    }
    

    
    
}
