/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;
/* Generated by Together */

/**
 * For a description of Permanent visitors, follow hyperlink to the Administration use case
 * for issuing a new Permanent visitor permit.
 */


public class Permanent_visitor_permit extends Permit {
    
    private String permitType;

    public Permanent_visitor_permit(String Cn) {
        super(Cn); 
        permitType = "Permanent Visitor";
        setPermitType(permitType);//Set the Permit Type
    }    

    @Override
    //ToString method for printing Permanent visitor permit
    public String toString() {
        return "Permanent_visitor_permit{" + "permitType=" + permitType + '}';
    }
}



