/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;
//This is done by Mohammed, Stirling ID:2732720
import java.util.Hashtable;
import java.util.Enumeration;


/* Generated by Together */
/**
 * Permit list manages the collection of permits currently issued and not yet
 * cancelled (or expired). It handles most of the use cases in the
 * Administration section. Note that each Permit must have a unique permit
 * holder name (so a HashTable is probably a good implementation of the
 * collection, with permit holder name as key).
 *
 * There will only be one instance of this class.
 */
public class Permit_list {

    private java.util.Hashtable lnkPermit;

    public Permit_list() {
        lnkPermit = new Hashtable(); //The hashtable that we have used
    }

    //Get Permit
    public Permit getPermit(String Cn) {
        return ((Permit) lnkPermit.get(Cn));
    }

    //CheckPermitted 
    public boolean checkPermitted(String RegNum) {
        return lnkPermit.containsKey(RegNum);
    }

    //Codes for adding the regular visitor to the Hashtable
    public Permit addR(String Cn, String On, String Vd, String Ed) {
        Regular_visitor_permit Regular_visitor_permit = new Regular_visitor_permit(Cn, On, Vd, Ed);
        lnkPermit.put(Cn, Regular_visitor_permit);
        System.out.println("The permit table for regular visitor: " + lnkPermit);
        return Regular_visitor_permit;
    }

    //Codes for adding the day visitor to the Hashtable
    public Permit addD(String Cn, String On, String Vd) {
        Day_visitor_permit Day_visitor_permit = new Day_visitor_permit(Cn, On, Vd);
        lnkPermit.put(Cn, Day_visitor_permit);
        System.out.println("The permit table for Day visitor: " + lnkPermit);
        return Day_visitor_permit;
    }

    //Codes for adding the parmanent visitor to the Hashtable
    public Permit addP(String Cn) {
        Permanent_visitor_permit Permanent_visitor_permit = new Permanent_visitor_permit(Cn);
        lnkPermit.put(Cn, Permanent_visitor_permit);
        System.out.println("The permit table for Permanent visitor: " + lnkPermit);
        return Permanent_visitor_permit;
    }

    //Codes for adding the university member to the Hashtable
    public Permit addU(String Cn, String On, String Vd) {
        University_member_permit University_member_permit = new University_member_permit(Cn, Vd);
        lnkPermit.put(Cn, University_member_permit);
        System.out.println("The permit table for University member: " + lnkPermit);
        return University_member_permit;
    }

    //Codes for printing the permit Hashtable
    public Hashtable printP(String Cn, String On, String Vd, String Ed) {
        Enumeration e = lnkPermit.elements();
        while (e.hasMoreElements()) {

            System.out.println("Permit elements are\n:" + e.nextElement());
        }
        return lnkPermit;
    }

    //Codes for removing the permit Hashtable
    public void removeP(String Cn, String On, String Vd, String Ed) {
        Object obj1 = lnkPermit.remove(Cn);
        System.out.println("Permit Data has removed from Hashtable" + obj1);
    }
}
