/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;

/* Generated by Together */
/**
 * For a description of Regular visitors, follow hyperlink to the Administration
 * use case for issuing a new Regular visitor permit.
 */
public class Regular_visitor_permit extends Permit {

    // Useful program constants
    private String owenerName;
    private String visitDay;
    private String endDay;
    private String permitType;

    public Regular_visitor_permit(String Cn, String On, String Vd, String Ed) {
        //initialize the values 
        super(Cn);
        owenerName = On;
        visitDay = Vd;
        endDay = Ed;
        permitType = "Regular Visitor";
        setPermitType(permitType);//Set the Permit Type
        setVisitday(Vd);//Set the visit day
        setEndday(Ed);//Set the end day
    }

    @Override
    //ToString method for printing Regular visitor permit
    public String toString() {
        return "Regular_visitor_permit{" + ", owenerName=" + owenerName + ", visitDay=" + visitDay + ", endDate=" + endDay + ", permitType=" + permitType + '}';
    }
}
