/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;

import java.util.Observable;
import java.util.Date;

/* Generated by Together */
/**
 * This class holds key control information for the operation of the barrier
 * system.
 *
 * It extends Observable, and notifies its observers whenever either the date
 * changes (caused by the Timer class), or the barrier system activity status
 * changes (caused by an instance of the Campus security class), or the barrier
 * event log changes (caused by an instance of the Barrier class).
 *
 * There will only be one instance of this class.
 */
public class System_status extends Observable {

    // Useful program constants
    private boolean systemActive = false;
    private String[] log;
    private boolean active = false;
    private boolean deactivate = true;
    private Date today;

    //Get the system status 
    public System_status() {
        today = new Date();
    }

    //Get Todays date
    public Date getToday() {
        return today;
    }

    //codes for active in class barrier 
    public void active() {
        systemActive = true;
        setChanged();
        notifyObservers();
    } // active

    //codes for deactivate in class barrier 
    public void deactivate() {
        systemActive = false;
        setChanged();
        notifyObservers();
    } // deactivate

    //Get system status
    public boolean getStatus() {
        return systemActive;
    } // getActive

    //Codes for add entry
    public boolean addEntry(String rNum) {
        return systemActive;
    } 
}
