/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;

/* Generated by Together */

/**
 * For a description of University member permits, follow hyperlink to the
 * Administration use case for issuing a new University member permit.
 */
public class University_member_permit extends Permit {

    // Useful program constants
    private Date lnkDate;
    private String permitType;
    private String visitDay;

    public University_member_permit(String Cn, String Vd) {
        //initialize the values
        super(Cn);
        visitDay = Vd;
        setPermitType(permitType);//Set the Permit Type
        setVisitday(visitDay);//Set the visit day
    }

    @Override
    //ToString method for printing University member permit
    public String toString() {
        return "University_member_permit{" + "lnkDate=" + lnkDate + ", visitDay=" + visitDay + '}';
    }
}
