/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;

/* Generated by Together */
/**
 * Each instance of Vehicle_info models an actual physical vehicle, so no two
 * instances may have the same registration number. There is no direct notation
 * for this. Instead the Vehicle list object collecting the Vehicles must
 * enforce it by checking new additions - the use of a HashTable in Vehicle_list
 * with the registration number as key is helpful with this.
 *
 * This class must contain at least the registration number, and may have any
 * other attributes that the University may from time to time find useful (such
 * as car make, model, colour...).
 */
public class Vehicle_info {

    /**
     * The vehicle's registration number.
     */
    // Useful program constants
    private String regNo;
    private String carc;
    private String carName;
    private Permit lnkPermit;
    private String NumEntries;
    private String NumWarning;

    public Vehicle_info(Permit permit, String c1, String c2, String c3, String c4, String c5) {
        lnkPermit = permit; //Permit hashtable
        regNo = c1; //regerstration number
        carc = c2; //Car color
        carName = c3;//Car name
        int i = 1;
        NumEntries = c4;
        NumWarning = c5;
    }

    //Get the permit type from lnkPermit hashtable
    public String getPermitType() {
        return lnkPermit.getPermitType();
    }

    public void setNumEntries(String NumEntries) {
        this.NumEntries = NumEntries;
    }

    public void setNumWarning(String NumWarning) {
        this.NumWarning = NumWarning;
    }

    public String getNumEntries() {
        return NumEntries;
    }

    public String getNumWarning() {
        return NumWarning;
    }

    
    
    
    /*//Get the number of entries
   public String getNumEntries() {
       return lnkVehicle.getNumEntries();
    }
    
    //Get the number of entries

    //Get the warnings
    public String getNumWarning() {
        return lnkVehicle.getNumWarning();
    }*/
   
       
    
    //Get permit from lnkPermit hashtable
    public Permit getPermit() {
        return lnkPermit;
    }

    //Get the visit day
    public String getVisitday() {
        return lnkPermit.getVisitday();
    }

    //Get the end day
    public String getEndday() {
        return lnkPermit.getEndday();
    }
//ToString method for printing the vehicle info

    @Override
    public String toString() {
        return "Vehicle_info{" + "regNo=" + regNo + ", carc=" + carc + ", carName=" + carName + ", lnkPermit=" + lnkPermit + ", NumEntries=" + NumEntries + ", NumWarning=" + NumWarning + '}';
    }
   
}
