/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.List;

/* Generated by Together */
/**
 * Vehicle list manages the collection of vehicles currently associated with
 * permits. It handles checks of whether vehicles are allowed through the
 * barriers, records warnings, and various other functions. Note that each
 * Vehicle_info object must have a unique registration number, to allow sensible
 * checking and recording of entries onto the campus (so a HashTable is probably
 * a good implementation of the collection, with registration number as key).
 *
 * There will only be one instance of this class.
 */
public class Vehicle_list {

    private java.util.Hashtable lnkVehicle;
    private Vehicle_info Vehicle_info;

    public Vehicle_list() {
        lnkVehicle = new Hashtable();
    }

    public void add(String RegNum, String CarC, String CarN, String CarT) {
        Vehicle_info = new Vehicle_info(RegNum, CarC, CarN, CarT);
        lnkVehicle.put(RegNum, Vehicle_info);
        System.out.println("The Vehicle table i: "+lnkVehicle);
    }

    public void print(String RegNum, String CarC, String CarN, String CarT) {
        Enumeration e = lnkVehicle.elements();
        while (e.hasMoreElements()){
        System.out.println("The elements are\n:" + e.nextElement());
       }
    }

    public boolean check(String RegNum, String CarC, String CarN, String CarT) {
     return lnkVehicle.containsKey(RegNum);
    }

    void modif(String RegNum, String CarC, String CarN, String CarT) { 
    }
}
