/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PACSUS.Java;

import java.util.Hashtable;
import java.util.Enumeration;

/* Generated by Together */

/**
 * Each instance of Vehicle_info models an actual physical vehicle, so no two
 * instances may have the same registration number. There is no direct notation
 * for this. Instead the Vehicle list object collecting the Vehicles must
 * enforce it by checking new additions - the use of a HashTable in Vehicle_list
 * with the registration number as key is helpful with this.
 *
 * This class must contain at least the registration number, and may have any
 * other attributes that the University may from time to time find useful (such
 * as car make, model, colour...).
 */
public class Vehicle_info {

    /**
     * The vehicle's registration number.
     */
    private String regNo;
    private String carc;
    private String carn;
    private String cart;       
    //private Permit lnkPermit;


    public Vehicle_info(String c1, String c2, String c3, String c4) {
       regNo = c1;
       carc = c2;
       carn = c3;
       cart = c4;         
    }

    @Override
    public String toString() {
        return "Vehicle_info{" + "regNo=" + regNo + ", car color=" + carc + ", car name=" + carn + ", car type=" + cart + '}';
    } 
    
}
